# Generated by Django 4.2.2 on 2023-07-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_category_comment_post_postcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='komment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_Commit',
            new_name='date_Commit',
        ),
    ]
